# Generated by Django 4.1.3 on 2022-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.CharField(max_length=100, verbose_name='время посещения'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, verbose_name='имя студента'),
        ),
    ]
