# Generated by Django 4.1.3 on 2022-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_feddback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
            ],
        ),
    ]
