# Generated by Django 4.1.3 on 2022-12-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_fullfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fullfeedback',
            new_name='Fullfb',
        ),
    ]
